#!/usr/bin/perl

use strict;
use DB_File;
use DirHandle;
use FileHandle;
use File::Basename qw/ basename /;

=head1 NAME

makedb - ノード名の DB を作成する

=head1 SYNOPSIS

makedb file

=head1 DESCRIPTION

改造版 F<texi2html> によって生成された HTML には

    <META NAME="x-info-node" CONTENT="Introduction">

というノード名の情報が含まれている．カレントディレクトリのファイル中か
ら，この情報を取り出して，F<goto.cgi> が使える DB を作成する．

=cut

&main( @ARGV );

sub main {
    my( $target ) = @_;

    my %table;
    tie( %table, 'DB_File', $target, O_CREAT )
	or die "Can't create file($target): $!\n";

    my $dir = DirHandle->new( "." ) or die;
    for my $file ( grep( /\.html\Z/, $dir->read ) ) {
	my $name = &basename( $file );
	$name =~ s/(_(abt|fot|ovr|toc|\d+))?\.html\Z//;
	my $fh = FileHandle->new( $file, "r" ) or die;
	while ( <$fh> ) {
	    if ( m/^<META NAME="x-info-node" CONTENT="(.*?)">$/ ) {
		print "$file:\t($name)$1\n";
		$table{$name,$1} = $file;
		last;
	    }
	}
	$fh->close;
    }

    untie %table;
}

=head1 AUTHOR

=over 4

=item TSUCHIYA Masatoshi <tsuchiya@namazu.org>

=back

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2, or (at your option)
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, you can either send email to this
program's maintainer or write to: The Free Software Foundation,
Inc.; 59 Temple Place, Suite 330; Boston, MA 02111-1307, USA.

Last Update: $Date$

=cut
